services:
  backend:
    build:
      context: ./wedding-site-be
    environment:
      - PORT=${BE_PORT}
      - API_URL=${BE_API_URL}
      - ENVIRONMENT=${BE_ENVIRONMENT}
  frontend:
    build:
      context: ./wedding-site
    ports:
      - 80:80
      - 443:443
