services:
  backend:
    build:
      context: ./wedding-site-be
    image: backend:latest
    environment:
      - PORT=${BE_PORT}
      - API_URL=${BE_API_URL}
      - ENVIRONMENT=${BE_ENVIRONMENT}
    restart: on-failure
  frontend:
    build:
      context: ./wedding-site
    image: frontend:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./wedding-site/nginx/:/etc/nginx/:rw
      - /var/www/certbot/:/var/www/certbot/:ro
    # - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    # - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
  certbot:
    image: certbot/certbot:latest
    profiles: [certbot]
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
