services:
  backend:
    build:
      context: ./wedding-site-be
    image: backend:latest
    environment:
      - PORT=${BE_PORT}
      - API_URL=${BE_API_URL}
      - ENVIRONMENT=${BE_ENVIRONMENT}
    restart: on-failure
  frontend:
    build:
      context: ./wedding-site
    image: frontend:latest
    ports:
      - 80:80
      - 443:443
    restart: on-failure
