name: Try Clone
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        timeout-minutes: 10
        run: docker compose build

      - name: Transfer Docker image to remote server
        timeout-minutes: 30
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          docker save frontend backend | ssh -o StrictHostKeyChecking=no -C ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} docker load

      - name: Update Repo & Deploy
        timeout-minutes: 60
        uses: appleboy/ssh-action@v0.1.2
        env:
          BE_PORT: ${{ secrets.BE_PORT }}
          BE_API_URL: ${{ secrets.BE_API_URL }}
          BE_ENVIRONMENT: ${{ secrets.BE_ENVIRONMENT }}
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          envs: APP_PORT,APP_API_URL,APP_ENVIRONMENT
          command_timeout: 60m
          script: |
            if cd repo; then git pull; else git clone git@github.com:mastree/wedding-site-app.git repo; cd repo; fi
            git submodule update --init --recursive --remote
            BE_PORT=${BE_PORT} BE_API_URL=${BE_API_URL} BE_ENVIRONMENT=${BE_ENVIRONMENT} docker compose up -d
            docker image prune -f
